### ISSUE TITLE
Resizing the image while cropping reduces the image quality

### ISSUE THREAD

**Issue by javidnoutash** [Srinija/SwiftCamScanner#1]
Thanks for the great piece of code.

The CropView passes the new image size to OpenCV based on the screen size, this reduces the quality of the cropped image very much.

My suggestion would be to convert the cropCircle center points from device screen size to match the original image size and then pass them to OpenCV.

**Comment by Srinija** [comment]
Hi @javidnoutash 
Thanks for the suggestion! That worked. I changed the final image dimensions and scaled the corresponding coordinates. Seems to have fixed the blurring issue. Pushed it to v0.1.1
